### ISSUE TITLE
Aligning data to gene2vec_16906.npy 

### ISSUE THREAD

**Issue by lavanyanemani96** [TranslationalBioinformaticsUnit/scbert-reusability#3]
How did you align the Neurips data to have the same order of genes as in gene2vec_16906.npy

**Comment by AlbertoMaillo** [comment]
Hello!! It is essential to use the HGNC symbols as gene ids. Located in .var from your h5ad file. You can then use it as input in their preprocess.py script https://github.com/TencentAILabHealthcare/scBERT/blob/master/preprocess.py. Hope it works for you.
